---

- name: Check if OS distribution is some Debian kind
  fail:
    msg: "OS distribution {{ ansible_os_family }} is not Debian family!"
  when: (not ansible_os_family == 'Debian')
  tags:
    - install

- name: Check if kind already installed into {{ kind_install_dir }}
  stat:
    path: "{{ kind_install_dir }}/kind"
  register: kind_status
  tags:
    - always

- name: Kind is not installed
  fail:
    msg: "Kind is not installed under the specified location {{ kind_install_dir }}/kind!"
  when: not kind_status.stat.exists
  tags:
    - create
    - delete

- name: Check installed kind version
  shell: "{{ kind_install_dir }}/kind --version | awk -F ' ' '{print \"v\"$3}'"
  changed_when: false
  register: kind_installed_version
  when: kind_status.stat.exists
  tags:
    - always

- name: Get latest kind release
  uri:
    url: "{{ kind_git }}/releases/latest"
    return_content: true
    body_format: json
  register: kind_latest_release
  when: kind_version == 'latest'
  tags:
    - install

- name: Set version to install
  set_fact:
    kind_version: "{{ kind_latest_release.json.tag_name }}"
  when: kind_version == 'latest'
  tags:
    - install

- name: Installation will be skipped
  debug:
    msg: "Installation will be skipped, the version {{ kind_version }} specified is already installed!"
  when: kind_version == kind_installed_version.stdout
  tags:
    - install